# Generated by Django 5.0.2 on 2024-02-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                ("type", models.CharField(db_column="TYPE", max_length=255)),
                ("name", models.CharField(db_column="NAME", max_length=255)),
                ("date_start", models.DateField(db_column="DATE_START")),
                ("date_end", models.DateField(db_column="DATE_END")),
                ("in_site", models.CharField(db_column="IN_SITE", max_length=255)),
                ("in_name", models.CharField(db_column="IN_NAME", max_length=255)),
                (
                    "course_code",
                    models.CharField(
                        blank=True, db_column="COURSE_CODE", max_length=1, null=True
                    ),
                ),
            ],
            options={
                "db_table": "ACTIVITY",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "ADMIN",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Attends",
            fields=[
                ("activity_id", models.IntegerField(db_column="ACTIVITY_ID")),
                (
                    "student_id",
                    models.IntegerField(
                        db_column="STUDENT_ID", primary_key=True, serialize=False
                    ),
                ),
            ],
            options={
                "db_table": "ATTENDS",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "course_code",
                    models.CharField(
                        db_column="COURSE_CODE",
                        max_length=1,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "db_table": "COURSE",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Gives",
            fields=[
                ("activity_id", models.IntegerField(db_column="ACTIVITY_ID")),
                (
                    "teacher_id",
                    models.IntegerField(
                        db_column="TEACHER_ID", primary_key=True, serialize=False
                    ),
                ),
            ],
            options={
                "db_table": "GIVES",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Professor",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "PROFESSOR",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Registered",
            fields=[
                (
                    "course_code",
                    models.CharField(db_column="COURSE_CODE", max_length=1),
                ),
                (
                    "id",
                    models.IntegerField(
                        db_column="ID", primary_key=True, serialize=False
                    ),
                ),
            ],
            options={
                "db_table": "REGISTERED",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                ("name", models.CharField(db_column="NAME", max_length=255)),
                (
                    "site",
                    models.CharField(
                        db_column="SITE",
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "db_table": "ROOM",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Sees",
            fields=[
                (
                    "announcement_id",
                    models.IntegerField(
                        db_column="ANNOUNCEMENT_ID", primary_key=True, serialize=False
                    ),
                ),
                ("user_id", models.IntegerField(db_column="USER_ID")),
            ],
            options={
                "db_table": "SEES",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "student_number",
                    models.CharField(
                        blank=True, db_column="STUDENT_NUMBER", max_length=1, null=True
                    ),
                ),
                ("noma", models.CharField(db_column="NOMA", max_length=1)),
            ],
            options={
                "db_table": "STUDENT",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "tutor",
                    models.IntegerField(blank=True, db_column="TUTOR", null=True),
                ),
                (
                    "professor",
                    models.IntegerField(blank=True, db_column="PROFESSOR", null=True),
                ),
            ],
            options={
                "db_table": "TEACHER",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tutor",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "TUTOR",
                "managed": False,
            },
        ),
    ]
