# Generated by Django 5.0.2 on 2024-03-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                ("title", models.CharField(db_column="TITLE", max_length=255)),
                ("description", models.TextField(db_column="DESCRIPTION")),
                ("pub_date", models.DateField(db_column="PUB_DATE")),
            ],
            options={
                "db_table": "ANNOUNCEMENT",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                ("content", models.TextField(db_column="CONTENT")),
                ("date", models.DateField(db_column="DATE")),
            ],
            options={
                "db_table": "MESSAGE",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                ("e_mail", models.CharField(db_column="E_MAIL", max_length=255)),
                ("name", models.CharField(db_column="NAME", max_length=64)),
                ("first_name", models.CharField(db_column="FIRST_NAME", max_length=64)),
                ("pwd", models.CharField(db_column="PWD", max_length=64)),
            ],
            options={
                "db_table": "USER",
                "managed": False,
            },
        ),
    ]
